services:

  # AUTH SERVICE DATABASE
  auth-service-db:
    image: postgres:17.4-alpine
    env_file: 
      - ./services/auth-service/.env
    environment:
    - POSTGRES_DB=auth_service_db
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASSWORD} 
    volumes:
      - ./services/auth-service/logs:/var/log/postgresql
      - auth-data:/var/lib/postgresql/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d auth_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # AUTH SERVICE API
  auth-service-api:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
      - .env
    volumes:
      - ./services/auth-service/logs:/home/appuser/app/logs
      - ./libs:/home/appuser/app/libs
    depends_on:
      auth-service-db:
        condition: service_healthy
    networks:
      - oti-network
      
      # COURSE SERVICE DATABASE
  course-service-db:
    image: postgres:17.4-alpine
    env_file: 
      - ./services/course-service/.env
    environment:
    - POSTGRES_DB=course_service_db
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASSWORD} 
    volumes:
      - course-data:/var/lib/postgresql/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d course_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  # COURSE SERVICE API
  course-service-api:
    build: ./services/course-service
    env_file:
      - ./services/course-service/.env
      - .env
    volumes:
      - ./services/course-service/logs:/home/appuser/app/logs
      - ./libs:/home/appuser/app/libs
    depends_on:
      course-service-db:
        condition: service_healthy
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # PACKAGE SERVICE DATABASE
  package-service-db:
    image: postgres:17.4-alpine
    env_file: 
      - ./services/package-service/.env
    environment:
    - POSTGRES_DB=package_service_db
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASSWORD} 
    volumes:
      - package-data:/var/lib/postgresql/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d package_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  # PACKAGE SERVICE API
  package-service-api:
    build: ./services/package-service
    env_file:
      - ./services/package-service/.env
      - .env
    volumes:
      - ./services/package-service/logs:/home/appuser/app/logs
      - ./libs:/home/appuser/app/libs
    depends_on:
      package-service-db:
        condition: service_healthy
      course-service-api:
        condition: service_healthy
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8005/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  # PAYMENT SERVICE DATABASE
  payment-service-db:
    image: postgres:17.4-alpine
    env_file: 
      - ./services/payment-service/.env
    environment:
    - POSTGRES_DB=payment_service_db
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASSWORD} 
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d payment_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # PAYMENT & ENROLLMENT SERVICE API
  payment-service-api:
    build: ./services/payment-service
    env_file:
      - ./services/payment-service/.env
      - .env
    volumes:
      - ./services/payment-service/logs:/home/appuser/app/logs
      - ./libs:/home/appuser/app/libs
    depends_on:
      payment-service-db:
        condition: service_healthy
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8006/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  # RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - oti-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # EMAIL SERVICE API
  email-service-api:
    build: ./services/email-service
    env_file:
      - ./services/email-service/.env
      - .env
    volumes:
      - ./services/email-service/logs:/app/logs
      - ./libs:/app/libs
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-guest}:${RABBITMQ_PASSWORD:-guest}@rabbitmq:5672
    depends_on:
      api-gateway:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8008/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

      
  api-gateway:
      build: ./api-gateway
      ports:
        - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
      env_file:
        - .env
        - ./api-gateway/.env
      volumes:
      - ./api-gateway/logs:/usr/src/app/logs
      depends_on:
        redis:
          condition: service_healthy
      networks:
        - oti-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:${API_GATEWAY_PORT}/health"]
        interval: 30s
        timeout: 10s
        retries: 3

networks:
  oti-network:
    driver: bridge

volumes:
  auth-data:
  course-data:
  package-data:
  payment-data:
  enrollment-data:
  redis-data:
  rabbitmq-data: