services:

  # AUTH SERVICE DATABASE
  auth-service-db:
    image: postgres:17.4-alpine
    env_file: 
      - ./services/auth-service/.env
    environment:
    - POSTGRES_DB=auth_service_db
    - POSTGRES_USER=${PG_USER}
    - POSTGRES_PASSWORD=${PG_PASSWORD} 
    volumes:
      - ./services/auth-service/logs:/var/log/postgresql
      - auth-data:/var/lib/postgresql/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d auth_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # AUTH SERVICE API
  auth-service-api:
    build: ./services/auth-service
    env_file:
      - ./services/auth-service/.env
      - .env
    volumes:
      - ./services/auth-service/logs:/home/appuser/app/logs
      - ./libs:/home/appuser/app/libs
    depends_on:
      auth-service-db:
        condition: service_healthy
    networks:
      - oti-network
      
  # Redis cache service
  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - oti-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

      
  api-gateway:
      build: ./api-gateway
      ports:
        - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
      env_file:
        - .env
        - ./api-gateway/.env
      volumes:
      - ./api-gateway/logs:/usr/src/app/logs
      depends_on:
        redis:
          condition: service_healthy
      networks:
        - oti-network
      restart: unless-stopped
      healthcheck:
        test: ["CMD", "wget", "-qO-", "http://localhost:${API_GATEWAY_PORT}/health"]
        interval: 30s
        timeout: 10s
        retries: 3

  # Nginx API Gateway
  nginx-gateway:
    image: nginx:1.25-alpine
    ports:
      - "${NGINX_API_GATEWAY_PORT:-8080}:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - api-gateway
      - auth-service-api
    networks:
      - oti-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  oti-network:
    driver: bridge

volumes:
  auth-data:
  redis-data: