name: oti-academy-course
services:
  course-service:
    container_name: course-service
    build:
      context: .
      dockerfile: Dockerfile
    image: oti-academy/course-service:latest    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: unless-stopped
