name: oti-academy-payment
services:
  payment-service:
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    image: oti-academy/payment-service:latest    
    ports:
      - "8006:8006"
    env_file:
      - .env
    restart: unless-stopped
